### ISSUE TITLE
English translated documentation?

### ISSUE THREAD

**Issue by HunnyBon** [WesleiRamos/Godot-Rich-Presence#1]
Hey, I'm interested in using your library for a game in Godot, but it's difficult to understand with something like Google translate, I think for many people including myself, they could benefit from an English documentation.

**Comment by WesleiRamos** [comment]
Hello, I apologize, I didn't write in English because I don't have a good knowledge of the english language, but I will try translate soon, the docs is basically the same from https://discordapp.com/developers/docs/rich-presence/how-to, you can see the example in https://github.com/WesleiRamos/Godot-Rich-Presence/blob/master/example/scripts/richpresence.gd, it's just that.

**Comment by WesleiRamos** [comment]
Translation added, I think I can close this issue.

**Comment by tessamerrill** [comment]
I'm trying to implement this into my project, but I don't see the `bin/librichpresence.gdns` anywhere. Where do I get it, because I'm sure its an important part to this repo.

 Thanks.

**Comment by WesleiRamos** [comment]
> I'm trying to implement this into my project, but I don't see the `bin/librichpresence.gdns` anywhere. Where do I get it, because I'm sure its an important part to this repo.
> 
> Thanks.

Please see [gdnlib file](https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/gdnative-c-example.html#creating-the-gdnativelibrary-gdnlib-file) and [gdns file](https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/gdnative-c-example.html#creating-the-nativescript-gdns-file)
